"""adding-soils

Revision ID: 451e47293236
Revises: 5692b943fd4c
Create Date: 2023-06-14 18:28:46.933260

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '451e47293236'
down_revision = '5692b943fd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('percent_sand', sa.Float(), nullable=False),
    sa.Column('percent_silt', sa.Float(), nullable=False),
    sa.Column('percent_clay', sa.Float(), nullable=False),
    sa.Column('cec', sa.Float(), nullable=False),
    sa.Column('bdod', sa.Float(), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('soc', sa.Float(), nullable=False),
    sa.Column('phh2o', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE soils SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soils')
    # ### end Alembic commands ###
